---
title: "Robberies in Toronto"
author: "Joe Bloggs"
date: "`r format(Sys.Date(), '%e %B %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sf)
library(tidyverse)
```

```{r load-data, cache=TRUE}
# Load robbery data
robberies <- read_sf("https://github.com/mpjashby/crimemapping/raw/main/inst/extdata/toronto_robberies.gpkg") %>% 
  janitor::clean_names() %>% 
  st_transform(3978)

# Load divisional boundaries
divisions_dir <- str_glue("{tempdir()}/divisions")
divisions_file <- str_glue("{tempdir()}/divisions.zip")
download.file(
  url = "https://github.com/mpjashby/crimemapping/raw/main/inst/extdata/toronto_police_divisions.zip",
  destfile = divisions_file
)
unzip(divisions_file, exdir = divisions_dir)
divisions <- str_glue("{divisions_dir}/Police Boundaries Data.shp") %>% 
  read_sf() %>% 
  janitor::clean_names() %>% 
  st_transform(3978) %>% 
  select(division = field_6)
```

```{r wrangle-data}
# Count number of robberies in each division
robbery_count <- robberies %>% 
  mutate(year = as.numeric(str_sub(occurrencedate, end = 4))) %>% 
  st_join(divisions) %>% 
  st_drop_geometry() %>% 
  count(division, year)

# Convert that data into a format that is suitable for displaying in a table
robbery_table <- robbery_count %>% 
  # Calculate the mean number of robberies in each division each year
  group_by(division) %>% 
  mutate(mean_count = mean(n)) %>% 
  # Arrange the divisions by mean count of robberies in descending order
  arrange(desc(mean_count)) %>% 
  ungroup() %>% 
  # Convert the data to wide format for easier display
  pivot_wider(names_from = year, values_from = n, values_fill = 0)
```

This table shows the number of robberies in each Toronto Police Service division 
in each year from `r min(pluck(robbery_count, "year"))` to 
`r max(pluck(robbery_count, "year"))`. During that time, on average Division
`r pluck(robbery_table, "division", 1)` had the highest number of robberies 
(`r scales::comma(pluck(robbery_table, "mean_count", 1), accuracy = 1)` per
year).

```{r divisional-table}
robbery_table %>% 
  # Remove columns we don't want to include in the table
  select(-mean_count) %>% 
  # Format the table for nicer display
  knitr::kable()
```
